-- MySQL Script generated by MySQL Workbench
-- Tue Jun 24 19:25:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cafeElBuenSabor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cafeElBuenSabor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cafeElBuenSabor` DEFAULT CHARACTER SET utf8 ;
USE `cafeElBuenSabor` ;

-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `precio` DECIMAL(15,2) NOT NULL,
  `stock` INT NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `idCategoria` INT NOT NULL,
  `imagen` VARCHAR(500) NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_productos_categorias1_idx` (`idCategoria` ASC),
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `cafeElBuenSabor`.`categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`mesas` (
  `idMesa` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idMesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`roles` (
  `idRoll` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idRoll`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaIngreso` DATETIME NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NULL,
  `idRoll` INT NOT NULL,
  `contraseña` VARCHAR(150) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_roles1_idx` (`idRoll` ASC),
  CONSTRAINT `fk_usuario_roles1`
    FOREIGN KEY (`idRoll`)
    REFERENCES `cafeElBuenSabor`.`roles` (`idRoll`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `idMesa` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedidos_mesas1_idx` (`idMesa` ASC),
  INDEX `fk_pedidos_usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_pedidos_mesas1`
    FOREIGN KEY (`idMesa`)
    REFERENCES `cafeElBuenSabor`.`mesas` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `cafeElBuenSabor`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`productos_has_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`productos_has_pedidos` (
  `idProducto` INT NOT NULL,
  `idPedido` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `subTotal` DECIMAL(15,2) NOT NULL,
  `precioVenta` INT NOT NULL,
  `nota` VARCHAR(250) NULL,
  PRIMARY KEY (`idProducto`, `idPedido`),
  INDEX `fk_productos_has_pedidos_pedidos1_idx` (`idPedido` ASC),
  INDEX `fk_productos_has_pedidos_productos1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_productos_has_pedidos_productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `cafeElBuenSabor`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_pedidos_pedidos1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `cafeElBuenSabor`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`ventas` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `total` DECIMAL(15,2) NULL,
  `pedidos_idPedido` INT NOT NULL,
  PRIMARY KEY (`idVenta`, `pedidos_idPedido`),
  INDEX `fk_ventas_pedidos1_idx` (`pedidos_idPedido` ASC),
  CONSTRAINT `fk_ventas_pedidos1`
    FOREIGN KEY (`pedidos_idPedido`)
    REFERENCES `cafeElBuenSabor`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`ingredientes` (
  `idingrediente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(250) NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idingrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`productos_has_ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`productos_has_ingredientes` (
  `idProducto` INT NOT NULL,
  `idIngredienes` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `idIngredienes`),
  INDEX `fk_productos_has_ingredientes_ingredientes1_idx` (`idIngredienes` ASC),
  INDEX `fk_productos_has_ingredientes_productos1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_productos_has_ingredientes_productos1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `cafeElBuenSabor`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_ingredientes_ingredientes1`
    FOREIGN KEY (`idIngredienes`)
    REFERENCES `cafeElBuenSabor`.`ingredientes` (`idingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`qr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`qr` (
  `idQr` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NOT NULL,
  `codigo` VARCHAR(200) NOT NULL,
  `horaInicio` DATETIME NOT NULL,
  `horaFinal` DATETIME NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idQr`),
  UNIQUE INDEX `idQr_UNIQUE` (`idQr` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafeElBuenSabor`.`qr_has_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafeElBuenSabor`.`qr_has_pedidos` (
  `idQr` INT NOT NULL,
  `idPedido` INT NOT NULL,
  PRIMARY KEY (`idQr`, `idPedido`),
  INDEX `fk_qr_has_pedidos_pedidos1_idx` (`idPedido` ASC),
  INDEX `fk_qr_has_pedidos_qr1_idx` (`idQr` ASC),
  CONSTRAINT `fk_qr_has_pedidos_qr1`
    FOREIGN KEY (`idQr`)
    REFERENCES `cafeElBuenSabor`.`qr` (`idQr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qr_has_pedidos_pedidos1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `cafeElBuenSabor`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
